import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "joinmarraiges",
  description: "Generated by create next app",
  keywords: [
    "How to attend an Indian wedding as a foreigner",
    "Participate in Indian wedding ceremony",
    "Join an Indian wedding in India",
    "Indian wedding experience",
    "Attend Indian wedding",
    "Traditional Indian wedding",
    "Cultural travel India",
    "Participate in Indian wedding ceremony",
    "Indian wedding cultural experience for travelers",
    "Indian wedding tourism",
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <head>
     
      <meta name="keywords" content='visa consults' />

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
